# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  httpapi-authorizer-lambda

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
Resources:
  MyApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      Auth:
        DefaultAuthorizer: MyLambdaRequestAuthorizer
        Authorizers:
          MyLambdaRequestAuthorizer:
            FunctionArn: !GetAtt MyAuthFunction.Arn
            Identity:
              Headers:
                - Authorization
            AuthorizerPayloadFormatVersion: 2.0
            EnableSimpleResponses: true
            EnableFunctionDefaultPermissions: true #Especifique esta propiedad para truecrear permisos automáticamente entre su recurso API HTTP y su autorizador Lambda.
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/
      Handler: app.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        HelloWorldApi:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
            ApiId:
              Ref: MyApi
            PayloadFormatVersion: "2.0"
  MyAuthFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/handlers/
      Handler: authorizer.handler
      Runtime: nodejs16.x
Outputs:
  Region:
    Description: "Region"
    Value: !Ref AWS::Region
  ApiId:
    Description: "API ID"
    Value: !Ref MyApi
  ApiUrl:
    Description: "API endpoint URL for Prod environment test"
    Value: !Sub 'https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'